Wba.Oefening.RateAMovie.Web/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Wba.Oefening.RateAMovie.Web.Data;
using Wba.Oefening.RateAMovie.Web.Models;
using Wba.Oefening.RateAMovie.Web.ViewModels;

namespace Wba.Oefening.RateAMovie.Web.Controllers
{
    public class CartController : Controller
    {
        private readonly MovieContext _movieContext;

        public CartController(MovieContext movieContext)
        {
            _movieContext = movieContext;
        }

        [HttpGet]
        public IActionResult Index()
        {
            //create viewmodel
            var cartIndexViewModel = new CartIndexViewModel();
            cartIndexViewModel.Items = new List<MovieItem>();

            //get cart viewmodel from session if exists
            if (HttpContext.Session.Keys.Any(k => k.Equals("cartItems")))
            {
                //get the serialized viewmodel
                var serializedCartIndexViewModel = HttpContext.Session.GetString("cartItems");
                //deserialize it
                cartIndexViewModel = JsonConvert
                    .DeserializeObject<CartIndexViewModel>(serializedCartIndexViewModel);
                //calculate total
                cartIndexViewModel.Total = cartIndexViewModel.Items.Sum(i => i.Price);
            }

            //pass to the view
            return View(cartIndexViewModel);
        }
        [HttpGet]
        public async Task<IActionResult> Add(long id) 
        {
            //create viewmodel
            var cartIndexViewModel = new CartIndexViewModel();
            cartIndexViewModel.Items = new List<MovieItem>();
            //get the movie
            var movie = await _movieContext
                .Movies.FirstOrDefaultAsync(m => m.Id == id);
            //check if null
            if(movie == null)
            {
                return NotFound();
            };
            //get cart from session
            if(HttpContext.Session.Keys.Any(k => k.Equals("cartItems")))
            {
                //get the serialized viewmodel
                var serializedCartIndexViewModel = HttpContext.Session.GetString("cartItems");
                //deserialize it
                cartIndexViewModel = JsonConvert
                    .DeserializeObject<CartIndexViewModel>(serializedCartIndexViewModel);
            }
            //check if movie in cart => increment quantity
            var item = cartIndexViewModel.Items.FirstOrDefault(m => m.Id == id);
            if (item != null)
            {
                //increment quantity
                item.Quantity++;
                item.Price = item.Quantity * 25;
            }
            else
            {
                //add movie to cart viewmodel
                cartIndexViewModel.Items.Add(
                    new MovieItem
                    {
                        Id = id,
                        Title = movie.Title,
                        Price = 25,
                        Quantity = 1
                    });
            }
            //add to session
            HttpContext.Session
                .SetString("cartItems", JsonConvert.SerializeObject(cartIndexViewModel));
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public async Task<IActionResult> Remove(long id)
        {
            //create viewmodel
            var cartIndexViewModel = new CartIndexViewModel();
            cartIndexViewModel.Items = new List<MovieItem>();
            //get the movie
            var movie = await _movieContext
                .Movies.FirstOrDefaultAsync(m => m.Id == id);
            //check if null
            if (movie == null)
            {
                return NotFound();
            };
            //get cart from session
            if (HttpContext.Session.Keys.Any(k => k.Equals("cartItems")))
            {
                //get the serialized viewmodel
                var serializedCartIndexViewModel = HttpContext.Session.GetString("cartItems");
                //deserialize it
                cartIndexViewModel = JsonConvert
                    .DeserializeObject<CartIndexViewModel>(serializedCartIndexViewModel);
                
                //check if movie in cart => decrement quantity
                var item =  cartIndexViewModel.Items.FirstOrDefault(i => i.Id == id);
                if(item.Quantity > 1)
                {
                    item.Quantity--;
                    item.Price = 25 * item.Quantity;
                }
                else
                {
                    cartIndexViewModel.Items.Remove(item);
                }
                //add to session
                HttpContext.Session
                    .SetString("cartItems", JsonConvert.SerializeObject(cartIndexViewModel));

                return RedirectToAction(nameof(Index));
            }
            //if no cart in session return notfound();
            return NotFound();
            
        }
    }
}

Wba.Oefening.RateAMovie.Web/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Wba.Oefening.RateAMovie.Core.Entities;
using Wba.Oefening.RateAMovie.Web.Data;
using Wba.Oefening.RateAMovie.Web.Models;
using Wba.Oefening.RateAMovie.Web.Services;
using Wba.Oefening.RateAMovie.Web.Services.Interfaces;
using Wba.Oefening.RateAMovie.Web.ViewModels;

namespace Wba.Oefening.RateAMovie.Web.Controllers
{
    public class MoviesController : Controller
    {
        private readonly MovieContext _movieContext;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IFileService _fileService;
        private readonly IFormHelpersService _formHelpersService;

        public MoviesController(MovieContext movieContext,
            IWebHostEnvironment webHostEnvironment,
            IFileService fileService,
            IFormHelpersService formHelpersService)
        {
            //injection here!!
            _movieContext = movieContext;
            _webHostEnvironment = webHostEnvironment;
            _fileService = fileService;
            _formHelpersService = formHelpersService;
        }
        public async Task<IActionResult> Index()
        {
            MoviesIndexViewModel moviesIndexViewModel = new();
            moviesIndexViewModel.Movies = await _movieContext
                .Movies
                .Select(m => new BaseViewModel
                {
                    Id = m.Id,
                    Item = m.Title
                }).ToListAsync();
            return View(moviesIndexViewModel);
        }

        
        [HttpGet]
        public IActionResult ConfirmDelete(long id)
        {
            ViewBag.Id = id;
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Delete(long id)
        {
            //delete movie
            var movie = await _movieContext
                .Movies
                .FirstOrDefaultAsync(m => m.Id == id);
            _movieContext.Movies.Remove(movie);
            await _movieContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Info(long id)
        {
            //get the movie and put in model
            MoviesInfoViewModel moviesInfoViewModel = new();
            var movie = await _movieContext.Movies
                .Include(m => m.Company)
                .Include(m => m.Actors)
                .Include(m => m.Directors)
                .FirstOrDefaultAsync(m => m.Id == id);
            moviesInfoViewModel.Id = movie?.Id ?? 0;
            moviesInfoViewModel.Title = movie?.Title ?? "<noTitle>";
            moviesInfoViewModel.ReleaseDate = movie?.ReleaseDate ?? DateTime.Now;
            moviesInfoViewModel.ImagePath = movie?.ImageFileName ?? $"{_webHostEnvironment.WebRootPath}/images/placeholder.jpg";
            moviesInfoViewModel.Company = new BaseViewModel 
            {
                Id = movie?.CompanyId ?? 0,
                Item = movie?.Company?.Name ?? "<NoName>" 
            };
            moviesInfoViewModel.Actors = movie?.Actors.Select(
                a => new BaseViewModel 
                {
                    Id = a?.Id,
                    Item = $"{a?.FirstName} {a?.LastName}"
                }
                );
            moviesInfoViewModel.Directors = movie?.Directors.Select(
                a => new BaseViewModel
                {
                    Id = a?.Id,
                    Item = $"{a?.FirstName} {a?.LastName}"
                }
                );
            ViewBag.PageTitle = movie?.Title ?? "<noTitle>";
            return View(moviesInfoViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            MoviesAddUpdateMovieViewModel moviesAddMovieViewModel = new();
            moviesAddMovieViewModel.Actors =
                await _formHelpersService.BuildCheckboxList(true);
            moviesAddMovieViewModel.Directors =
                await _formHelpersService.BuildCheckboxList(false);
            moviesAddMovieViewModel.Companies
                = await _formHelpersService.BuildCompanyList();
            moviesAddMovieViewModel.ReleaseDate = DateTime.Now.Date;
            return View(moviesAddMovieViewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(MoviesAddUpdateMovieViewModel moviesAddMovieViewModel)
        {

            //check custom errors
            if (moviesAddMovieViewModel.ReleaseDate > DateTime.Now)
            {
                ModelState.AddModelError("", "Releasedate must be in the past!");
            }
            if (!ModelState.IsValid)
            {
                moviesAddMovieViewModel.Companies
                = await _formHelpersService.BuildCompanyList();
                return View(moviesAddMovieViewModel);
            }
            //store movie here
            Movie newMovie = new();
            newMovie.Title = moviesAddMovieViewModel.Title;
            newMovie.CompanyId = moviesAddMovieViewModel.CompanyId;
            newMovie.ReleaseDate = moviesAddMovieViewModel.ReleaseDate;
            if (moviesAddMovieViewModel.Image != null)
            {
                //check file extension
                if(!Path.GetExtension(moviesAddMovieViewModel.Image.FileName).Equals(".jpg"))
                {
                    moviesAddMovieViewModel.Companies
                = await _formHelpersService.BuildCompanyList();
                    ModelState.AddModelError("", "Only jpg allowed!");
                    return View(moviesAddMovieViewModel);
                }
                //call StoreFile service method
                newMovie.ImageFileName = await _fileService.AddOrUpdateFile(moviesAddMovieViewModel.Image,
                    "movies", _webHostEnvironment);
            }
            //store actors
            var selectedActors = moviesAddMovieViewModel
                .Actors
                .Where(a => a.IsSelected == true).Select(a => a.Id);
            newMovie.Actors = await _movieContext
                .Actors
                .Where(a => selectedActors.Contains(a.Id)).ToListAsync();
            
            //store directors
            var selectedDirectors = moviesAddMovieViewModel
                .Directors.Where(d => d.IsSelected == true)
                .Select(d => d.Id);
            newMovie.Directors = await _movieContext
                .Directors
                .Where(d => selectedDirectors.Contains(d.Id)).ToListAsync();
            _movieContext.Movies.Add(newMovie);
            await _movieContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(long id)
        {
            //reuse the AddMovieViewModel
            MoviesAddUpdateMovieViewModel moviesUpdateMovieViewModel
                = new();
            //get the movie
            var movie = await _movieContext
                .Movies
                .Include(m => m.Actors)
                .Include(m => m.Directors)
                .FirstOrDefaultAsync(m => m.Id == id);
            //fill the model
            moviesUpdateMovieViewModel.Title = movie?.Title ?? "<NoTitle>";
            moviesUpdateMovieViewModel.ReleaseDate = movie?.ReleaseDate ?? DateTime.Today;
            moviesUpdateMovieViewModel.Id = movie?.Id ?? 0;
            moviesUpdateMovieViewModel.CompanyId = movie?.CompanyId ?? 0;
            //build the checkboxes
            moviesUpdateMovieViewModel.Actors
                = await _formHelpersService.BuildCheckboxList(true, movie);
            
            //directors
            moviesUpdateMovieViewModel.Directors
                = await _formHelpersService.BuildCheckboxList(false, movie);

            //build the companylist
            moviesUpdateMovieViewModel.Companies = await _formHelpersService
                .BuildCompanyList();
            return View(moviesUpdateMovieViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(MoviesAddUpdateMovieViewModel moviesUpdateMovieViewModel)
        {
            //do some custom checks
            if (moviesUpdateMovieViewModel.ReleaseDate > DateTime.Today)
            {
                ModelState.AddModelError("", "Dat must be in the past!");
            }
            if(moviesUpdateMovieViewModel.Image != null &&
                !Path.GetExtension(moviesUpdateMovieViewModel.Image?.FileName).Equals(".jpg"))
            {
                ModelState.AddModelError("", "image must be .jpg!");
            }
            if (!ModelState.IsValid)
            {
                //repopulate the company selectlist
                moviesUpdateMovieViewModel.Companies = await _formHelpersService
                    .BuildCompanyList();
                return View(moviesUpdateMovieViewModel);
            }
           
            //update movie
            var movie = await _movieContext
                .Movies
                .Include(m => m.Actors)
                .Include(m => m.Directors)
                .FirstOrDefaultAsync(m => m.Id == moviesUpdateMovieViewModel.Id);
            //update everything
            movie.Title = moviesUpdateMovieViewModel.Title;
            movie.ReleaseDate = moviesUpdateMovieViewModel.ReleaseDate;
            movie.CompanyId = moviesUpdateMovieViewModel.CompanyId;
            //actors
            var selectedActors = moviesUpdateMovieViewModel
                .Actors
                .Where(a => a.IsSelected == true)
                .Select(a => a.Id);
            movie.Actors =
                await _movieContext
                .Actors.Where(a => selectedActors.Contains(a.Id)).ToListAsync();

            //directors

Wba.Oefening.RateAMovie.Web/Views/Movies/Add.cshtml
@model MoviesAddUpdateMovieViewModel

<h2>Add a movie</h2>
<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<form asp-controller="Movies" asp-action="Add" method="post" enctype="multipart/form-data">
    <partial name="_MovieFormPartial" model="@Model" />
    <button type="submit" class="btn btn-primary">Save</button>
</form>

Wba.Oefening.RateAMovie.Web/Views/Movies/ConfirmDelete.cshtml
<div class="alert alert-primary" role="alert">
    Are you sure?
    <a asp-controller="Movies"
       asp-action="Index" class="btn btn-primary">No</a>
    <a asp-controller="Movies"
       asp-action="Delete"
       asp-route-id="@ViewBag.Id" class="btn btn-danger">Yes</a>
</div>

Wba.Oefening.RateAMovie.Web/Views/Movies/Edit.cshtml
@model MoviesAddUpdateMovieViewModel

<h2>Update movie</h2>
<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<form asp-controller="Movies" asp-action="Edit" method="post" enctype="multipart/form-data">
    <partial name="_MovieFormPartial" model="@Model" />
    <button type="submit" class="btn btn-primary">Save</button>
</form>

Wba.Oefening.RateAMovie.Web/Views/Movies/Index.cshtml
@model MoviesIndexViewModel

<h2>@ViewBag.PageTitle</h2>

<table class="table table-hover table-responsive">
    <tr>
        <th>Title</th>
        <th colspan="3">Action</th>
    </tr>
    @foreach(var movie in Model.Movies)
    { 
        <tr>
            <td>@movie.Item</td>

            <td colspan="3">
                <a asp-controller="Movies"
                   asp-action="Info"
                   asp-route-id="@movie.Id" class="btn btn-info">Info</a> ||
                <a asp-controller="Movies"
                   asp-action="Edit"
                   asp-route-id="@movie.Id" class="btn btn-primary">Edit</a> ||
                <a asp-controller="Movies"
                   asp-action="ConfirmDelete"
                   asp-route-id="@movie.Id" class="btn btn-danger">Delete</a>
                <a asp-controller="Cart"
                   asp-action="Add"
                   asp-route-id="@movie.Id" class="btn btn-danger">Add to cart</a>
            </td>
        </tr>
    }
</table>
<div>
    <a asp-controller="Movies"
       asp-action="Add"
       class="btn btn-outline-primary">Add a Movie</a>
</div>

Wba.Oefening.RateAMovie.Web/Views/Movies/Info.cshtml
@model MoviesInfoViewModel

<h2>@ViewBag.PageTitle</h2>
<div class="card text-center mx-auto" style="width: 22rem;">
    <img src="/images/movies/@Model.ImagePath" class="card-img-top" alt="...">
    <div class="card-body">
        <h5 class="card-title">@Model.Title</h5>
        <h6 class="card-subtitle mb-2 text-muted">@Model.ReleaseDate.ToString("dd/MM/yyyy")</h6>

        <dl>
            <dt>Company</dt>
            <dd>
                
                    <a asp-controller="Companies" asp-action="ShowInfo"
                       asp-route-id="@Model.Company.Id" class="card-link">@Model.Company.Item</a>
                
            </dd>
        </dl>
        <dl>
                <dt>Actor(s)</dt>
                @foreach (var actor in Model.Actors)
                {
                    <dd>
                        <a asp-controller="Actors" asp-action="ShowInfo"
                           asp-route-id="@actor.Id" class="card-link">@actor.Item</a>
                    </dd>
                }
            </dl>
            <dl>
                <dt>Director(s)</dt>
                @foreach (var director in Model.Directors)
                {
                    <a asp-controller="Directors" asp-action="ShowInfo"
                       asp-route-id="@director.Id" class="card-link">@director.Item</a>
                }
                
            </dl>
</div>
    <div class="card-footer">
        <a asp-controller="Movies"
           asp-action="Index" class="btn btn-primary">Back</a>
    </div>
</div>

Wba.Oefening.RateAMovie.Web/Views/Movies/_MovieFormPartial.cshtml
@model MoviesAddUpdateMovieViewModel
<div class="form-group">
    <label asp-for="Title"></label>
    <input asp-for="Title" class="form-control">
    <span asp-validation-for="Title" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="ReleaseDate"></label>
    <input asp-for="ReleaseDate" class="form-control">
    <span asp-validation-for="ReleaseDate" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="CompanyId"></label>
    <select class="form-control" asp-for="CompanyId" asp-items="@Model.Companies"></select>
</div>
<div class="form-group">
    @for (int i = 0; i < Model.Actors.Count; i++)
    {
        <label>@Model.Actors[i].Text</label>
        <input asp-for="@Model.Actors[i].IsSelected" />
        <input asp-for="@Model.Actors[i].Id" />
        <input asp-for="@Model.Actors[i].Text" />
    }
</div>
<div class="form-group">
    @for (int i = 0; i < Model.Directors.Count; i++)
    {
        <label>@Model.Directors[i].Text</label>
        <input asp-for="@Model.Directors[i].IsSelected" />
        <input asp-for="@Model.Directors[i].Id" />
        <input asp-for="@Model.Directors[i].Text" />
    }
</div>
<div class="form-group">
    <label asp-for="Image"></label>
    <input asp-for="Image" class="form-control">
    <span asp-validation-for="Image" class="text-danger"></span>
</div>